/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import com.sun.jmx.mbeanserver.Util;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author ehtis
 */
public class logout extends javax.swing.JFrame {
    /**
     * Creates new form LoginUI
     */
    rent_a_car obj; 
    Manager me;
    public logout(rent_a_car ob , Manager mme) {
        initComponents();
       obj=ob;
       me=mme;
       
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        popupMenu3 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        button1 = new java.awt.Button();

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        popupMenu3.setLabel("popupMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(69, 109, 170));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        button1.setLabel("EXIT");
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        // TODO add your handling code here:
         Connection con;
         Statement stmt;
//System.out.println("project.logout.button1MouseClicked()");
        try
        {
          
            String s="jdbc:derby://localhost:1527/rent";
             con=DriverManager.getConnection(s,"java","1234");
            stmt = con.createStatement(); 
            stmt.execute("DELETE FROM MANAGER");
            for (int i = 0; i < obj.Managers.size(); i++) 
            {
                Manager get=obj.Managers.get(i);
                stmt.execute("INSERT INTO MANAGER (ID, USER_ID, PASSWORD, NAME, ADDRESS, GENDER, PHONE, SALARY, ALLOWANCE, BONUS)"+" VALUES (" + get.id + ",'" + get.user_id +"','"+ get.password + "','" + get.name + "','" + get.address + "','" + get.gender + "'," + get.phone + "," + get.salary + "," + get.allowance + "," + get.bonus + ")");
            }
            stmt.execute("DELETE FROM DRIVER");
            for (int i = 0; i < obj.Drivers.size(); i++) 
            {
                Driver get=obj.Drivers.get(i);
                stmt.execute("INSERT INTO JAVA.DRIVER (ID, LIC, LIC_TYPE, NAME, ADDRESS, GENDER, PHONE, SALARY, ALLOWANCE, BONUS)"+" VALUES (" + get.id + ",'" + get.Licence +"','"+ get.Lic_type + "','" + get.name + "','" + get.address + "','" + get.gender + "'," + get.phone + "," + get.salary + "," + get.allowance + "," + get.bonus + ")");
            }
            stmt.execute("DELETE FROM VEHICLE");
            for (int i = 0; i < obj.Vehicles.size(); i++) 
            {
                Vehicle get=obj.Vehicles.get(i);
                stmt.execute("INSERT INTO JAVA.VEHICLE (ID, REG_NO, MODEL, COMPANY, PETROL, KM_DRIVEN, CURRENT_METER, AVERAGE, TYPE) "+" VALUES (" + get.Id + ",'" + get.Reg_no + "'," + get.model + ",'" + get.Brand + "'," + get.petrol + "," + get.km_driven + "," + get.meter + "," + get.average + ",'" + get.type + "')");
            }
            stmt.execute("DELETE FROM COMPANIES");
            for (int i = 0; i < obj.Companies.size(); i++) 
            {
                Company get=obj.Companies.get(i);
                stmt.execute("INSERT INTO JAVA.COMPANIES (ID, NAME, ADDRESS) "+" VALUES (" + get.id + ",'" + get.name + "','" + get.Address +"')");
            }
            stmt.execute("DELETE FROM CLIENT");
            for (int i = 0; i < obj.clients.size(); i++) 
            {
                Client get=obj.clients.get(i);
                stmt.execute("INSERT INTO JAVA.CLIENT (ID, NAME, ADDRESS, PHONE) "+" VALUES (" + get.id + ",'" + get.name + "','" + get.address +"'," +get.phone +")");
            }
            stmt.execute("DELETE FROM RENTAL");
            System.out.println(obj.Bookings.size());
            for (int i = 0; i < obj.Bookings.size(); i++) 
            {
                Booking g=obj.Bookings.get(i);
                Rental get=g.booking;
                
                stmt.execute("INSERT INTO JAVA.RENTAL (RENTAL_NO, VEH_ID, DRIVER_ID, MANAGER_ID, CLIENT_ID, PICK_UP_ADDRESS, USAGE_TERITORY, METER_OUT, METER_IN, KM_DRIVEN, TIME_USED, DATE_OUT, DATE_IN, DATE_USED, RATE_PER_KM, RATE_PER_HOUR, ALLOWANCE, TOLL_TAX, COMP_ID, EXTRA, TIME_OUT, TIME_IN, TOTAL_BILL) VALUES("+ get.Rental_id + "," + get.v_id + "," + get.dr_id + "," +  get.man_id + "," + get.cli_id + ",'" + get.pickup + "','" + get.usage + "'," + get.m_out + "," + get.m_in + "," + get.km_driven + "," + get.time_used + ",'" + get.date_out + "','" + get.date_in + "'," + 0 + "," + get.rate_p_km + "," + get.rate_p_hour + "," + get.allowance + "," +get.tolls  + "," + get.cmp_id + "," + get.extra + "," + get.time_out + "," + get.time_in + "," + get.Total_bill +")");               
                
            }
        }
         
        catch(SQLException e)
        {
            System.out.println(e);
        }
       
    }//GEN-LAST:event_button1MouseClicked

    
    public void main(rent_a_car ob,Manager loged) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new logout(ob,loged).setVisible(true);
                obj=ob;
                me=loged;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JPanel jPanel1;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private java.awt.PopupMenu popupMenu3;
    // End of variables declaration//GEN-END:variables

    void main(String start) {
        
        }
}
