/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.admin;

import Main.BL;
import Models.Manager;

/**
 *
 * @author gng
 */
public class EditManager extends javax.swing.JFrame {

    /**
     * Creates new form EditManager
     */
    Manager manager;

    public EditManager(Manager manager) {

        this.manager = manager;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        backButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        doneButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        cnicTextField = new javax.swing.JTextField();
        salaryTextField = new javax.swing.JTextField();
        bonusTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();
        genderComboBox = new javax.swing.JComboBox<>();
        passwordField = new javax.swing.JPasswordField();
        nameLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        usernameError = new javax.swing.JLabel();
        // Code adding the component to the
        passwordError = new javax.swing.JLabel();
        nameError = new javax.swing.JLabel();
        phoneError = new javax.swing.JLabel();
        addressError = new javax.swing.JLabel();
        cnicError = new javax.swing.JLabel();
        salaryError = new javax.swing.JLabel();
        bonusError = new javax.swing.JLabel();
        uniqueError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(69, 109, 170));
        jPanel6.setPreferredSize(new java.awt.Dimension(820, 560));

        jPanel7.setBackground(new java.awt.Color(177, 190, 224));

        jLabel3.setBackground(new java.awt.Color(105, 132, 207));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Edit Manager Details");

        backButton4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        backButton4.setText("Back");
        backButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(backButton4)
                .addGap(230, 230, 230)
                .addComponent(jLabel3)
                .addGap(279, 279, 279))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(backButton4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(177, 190, 224));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("ID:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Username:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Password:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Address:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Salary:  Rs.");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Bonus %:");

        doneButton.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        doneButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        doneButton.setText("Done");
        doneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doneButtonMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("CNIC #");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Gender:");

        idLabel.setText(Integer.toString(manager.getId()));

        usernameTextField.setText(manager.getUsername());

        cnicTextField.setText(manager.getCnic());

        salaryTextField.setText(Integer.toString(manager.getSalary()));

        bonusTextField.setText(Integer.toString(manager.getBonusPercentage()));

        addressTextArea.setColumns(20);
        addressTextArea.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        addressTextArea.setRows(5);
        addressTextArea.setText(manager.getAddress());
        jScrollPane1.setViewportView(addressTextArea);

        if(manager.getGender().equalsIgnoreCase("male")){
            genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female" }));
        }
        else{
            genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "female", "male" }));
        }

        Object a = manager.getGender();
        genderComboBox.setSelectedItem(a);

        passwordField.setText(manager.getPassword());

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameLabel.setText("Name:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Phone:");

        nameTextField.setText(manager.getName());

        phoneTextField.setText(manager.getPhone());

        usernameError.setForeground(new java.awt.Color(255, 0, 0));
        usernameError.setText("Username is required");
        usernameError.setVisible(false);

        passwordError.setForeground(new java.awt.Color(255, 0, 0));
        passwordError.setText("Password is required");
        passwordError.setVisible(false);

        nameError.setForeground(new java.awt.Color(255, 0, 0));
        nameError.setText("Name is required");
        nameError.setVisible(false);

        phoneError.setForeground(new java.awt.Color(255, 0, 0));
        phoneError.setText("Phone number is required");
        phoneError.setVisible(false);

        addressError.setForeground(new java.awt.Color(255, 0, 0));
        addressError.setText("Address is required");
        addressError.setVisible(false);

        cnicError.setForeground(new java.awt.Color(255, 0, 0));
        cnicError.setText("CNIC number is required");
        cnicError.setVisible(false);

        salaryError.setForeground(new java.awt.Color(255, 0, 0));
        salaryError.setText("Salary must be a number");
        salaryError.setVisible(false);

        bonusError.setForeground(new java.awt.Color(255, 0, 0));
        bonusError.setText("Bonus% must be a number");
        bonusError.setVisible(false);

        uniqueError.setForeground(new java.awt.Color(255, 0, 0));
        uniqueError.setText("Username already taken");
        uniqueError.setVisible(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genderComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cnicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(idLabel))
                                .addComponent(jLabel7)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(passwordField))
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1))
                            .addComponent(passwordError)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(uniqueError)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usernameError)))
                        .addGap(184, 184, 184)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(nameError)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(nameLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nameTextField))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(phoneTextField)))
                                .addGap(85, 85, 85))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(salaryTextField))
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(bonusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(phoneError)
                                    .addComponent(salaryError)
                                    .addComponent(bonusError))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cnicError)
                            .addComponent(addressError))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idLabel))
                .addGap(30, 30, 30)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameError)
                    .addComponent(nameError)
                    .addComponent(uniqueError))
                .addGap(3, 3, 3)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordError)
                    .addComponent(phoneError))
                .addGap(8, 8, 8)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(salaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salaryError)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(bonusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bonusError)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cnicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cnicError)
                .addGap(3, 3, 3)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButton4MouseClicked
        // TODO add your handling code here:
        AdminHome page = new AdminHome(manager);
        page.start();
        this.setVisible(false);
    }//GEN-LAST:event_backButton4MouseClicked

    private void doneButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneButtonMouseClicked
        // TODO add your handling code here:

        if (!usernameTextField.getText().isBlank()) {
            usernameError.setVisible(false);
            if (!passwordField.getText().isBlank()) {
                passwordError.setVisible(false);
                if (!nameTextField.getText().isBlank()) {
                    nameError.setVisible(false);
                    if (!phoneTextField.getText().isBlank()) {
                        phoneError.setVisible(false);
                        if (!addressTextArea.getText().isBlank()) {
                            addressError.setVisible(false);
                            if (!cnicTextField.getText().isBlank()) {
                                cnicError.setVisible(false);
                                if (!salaryTextField.getText().isBlank()) {
                                    if (salaryTextField.getText().matches("[0-9]+")) {
                                        salaryError.setVisible(false);
                                        if (!bonusTextField.getText().isBlank()) {
                                            if (bonusTextField.getText().matches("[0-9]+")) {
                                                bonusError.setVisible(false);

                                                manager.setUsername(usernameTextField.getText());
                                                manager.setPassword(passwordField.getText());
                                                manager.setName(nameTextField.getText());
                                                manager.setPhone(phoneTextField.getText());
                                                manager.setAddress(addressTextArea.getText());
                                                manager.setCnic(cnicTextField.getText());
                                                manager.setGender(String.valueOf(genderComboBox.getSelectedItem()));
                                                manager.setSalary(Integer.parseInt(salaryTextField.getText()));
                                                manager.setBonusPercentage(Integer.parseInt(bonusTextField.getText()));

                                                if (BL.getBllInstance().updateManager(manager)) {
                                                    uniqueError.setVisible(false);
                                                    AdminHome page = new AdminHome(manager);
                                                    page.start();
                                                    this.setVisible(false);
                                                } else {
                                                    uniqueError.setVisible(true);
                                                }
                                            } else {
                                                bonusError.setVisible(true);
                                            }
                                        } else {
                                            manager.setUsername(usernameTextField.getText());
                                            manager.setPassword(passwordField.getText());
                                            manager.setName(nameTextField.getText());
                                            manager.setPhone(phoneTextField.getText());
                                            manager.setAddress(addressTextArea.getText());
                                            manager.setCnic(cnicTextField.getText());
                                            manager.setGender(String.valueOf(genderComboBox.getSelectedItem()));
                                            manager.setSalary(Integer.parseInt(salaryTextField.getText()));
                                            manager.setBonusPercentage(Integer.parseInt(bonusTextField.getText()));

                                            if (BL.getBllInstance().updateManager(manager)) {
                                                AdminHome page = new AdminHome(manager);
                                                page.start();
                                                this.setVisible(false);
                                            } else {
                                                uniqueError.setVisible(true);
                                            }
                                        }
                                    } else {
                                        salaryError.setVisible(true);
                                    }
                                } else {
                                    if (!bonusTextField.getText().isBlank()) {
                                        if (bonusTextField.getText().matches("[0-9]")) {
                                            bonusError.setVisible(false);

                                            manager.setUsername(usernameTextField.getText());
                                            manager.setPassword(passwordField.getText());
                                            manager.setName(nameTextField.getText());
                                            manager.setPhone(phoneTextField.getText());
                                            manager.setAddress(addressTextArea.getText());
                                            manager.setCnic(cnicTextField.getText());
                                            manager.setGender(String.valueOf(genderComboBox.getSelectedItem()));
                                            manager.setSalary(Integer.parseInt(salaryTextField.getText()));
                                            manager.setBonusPercentage(Integer.parseInt(bonusTextField.getText()));

                                            if (BL.getBllInstance().updateManager(manager)) {
                                                AdminHome page = new AdminHome(manager);
                                                page.start();
                                                this.setVisible(false);
                                            } else {
                                                uniqueError.setVisible(true);
                                            }
                                        } else {
                                            bonusError.setVisible(true);
                                        }
                                    } else {
                                        manager.setUsername(usernameTextField.getText());
                                        manager.setPassword(passwordField.getText());
                                        manager.setName(nameTextField.getText());
                                        manager.setPhone(phoneTextField.getText());
                                        manager.setAddress(addressTextArea.getText());
                                        manager.setCnic(cnicTextField.getText());
                                        manager.setGender(String.valueOf(genderComboBox.getSelectedItem()));
                                        manager.setSalary(Integer.parseInt(salaryTextField.getText()));
                                        manager.setBonusPercentage(Integer.parseInt(bonusTextField.getText()));

                                        if (BL.getBllInstance().updateManager(manager)) {
                                            AdminHome page = new AdminHome(manager);
                                            page.start();
                                            this.setVisible(false);
                                        } else {
                                            uniqueError.setVisible(true);
                                        }
                                    }
                                }
                            } else {
                                cnicError.setVisible(true);
                            }
                        } else {
                            addressError.setVisible(true);
                        }
                    } else {
                        phoneError.setVisible(true);
                    }
                } else {
                    nameError.setVisible(true);
                }
            } else {
                passwordError.setVisible(true);
            }
        } else {
            usernameError.setVisible(true);
        }
        //update manager in DB function call here
    }//GEN-LAST:event_doneButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditManager(manager).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressError;
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JButton backButton4;
    private javax.swing.JLabel bonusError;
    private javax.swing.JTextField bonusTextField;
    private javax.swing.JLabel cnicError;
    private javax.swing.JTextField cnicTextField;
    private javax.swing.JButton doneButton;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameError;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel passwordError;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel phoneError;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel salaryError;
    private javax.swing.JTextField salaryTextField;
    private javax.swing.JLabel uniqueError;
    private javax.swing.JLabel usernameError;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
